### ISSUE TITLE
createEvent incomplete

### ISSUE THREAD

**Issue by roishmueli1** [yshur/eventbreak#10]
there is commit on creator beacuse its given error...
![image](https://user-images.githubusercontent.com/33421651/41104206-81dbe3ce-6a73-11e8-9513-003a3a298d1e.png)

**Comment by yshur** [comment]
I see that "creator" field doesnt exist anymore on createEvent function, you fixed it?
its my fault.
we need to think if we would like create event with all paramters in the first query to DB,
or that in the beginning we pass only few params, and update the rest afterwards.
we need to think also about what function has the responsibility to call to "createChat" function - if it client responsibility or that we need to call it within the createEvent function.
i prefer the second option

**Comment by roishmueli1** [comment]
done
