### ISSUE TITLE
implement api on data/index.js file

### ISSUE THREAD

**Issue by yshur** [yshur/eventbreak#2]
we need to know the params and the method for each api.
we will use in CRUD against mlab.
we need to think what we wand return back to user after each api - 
for example, after create event we need to return back event-id for user will can continue edit it

**Comment by yshur** [comment]
i started a few api for create & get from our collections.
we should add api for update collections - specially the events

**Comment by yshur** [comment]
i added declarations without implementation

**Comment by roishmueli1** [comment]
i added the updates functions to the routes... 
we need to implement , all of them are still empty.
in addtion, we need delete functions to make full CRUD

**Comment by yshur** [comment]
איזה באסה - עשיתי PULL ועדיין לא הכול התעדכן אצלי וסתם עבדתי על דברים שכבר
עשית.
פעם הבאה אני אוודא מול הגיטהאב שהתעדכן אצלי הכול

‫בתאריך שבת, 9 ביוני 2018 ב-23:38 מאת ‪roishmueli1‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by yshur** [comment]
אני סוגר את המשימה הזו בינתיים - היא הושלמה

**Comment by yshur** [comment]
זה כזה מסובך לעשות PULL
אני ניסיתי למזג את שני הבראנצ'ים שלי ושלך ואני לא מצליח לעשות PULL


‫בתאריך יום ב׳, 11 ביוני 2018 ב-0:39 מאת ‪Yair Shur‬‏ <‪yair.shur@gmail.com
‬‏>:‬

**Comment by yshur** [comment]
בסוף עשיתי כמוך - מחקתי ועשיתי clone מחדש

‫בתאריך יום ב׳, 11 ביוני 2018 ב-1:14 מאת ‪Yair Shur‬‏ <‪yair.shur@gmail.com
‬‏>:‬
