### ISSUE TITLE
fix connection between schemas

### ISSUE THREAD

**Issue by yshur** [yshur/eventbreak#4]
compiler doesnt compile this:
creator: {
            type: Schema.Types.ObjectId,
            ref:'user'
        },
the failure is:
![image](https://user-images.githubusercontent.com/23276841/40946774-0b5bba38-6868-11e8-92ef-9491e8cbf20c.png)

**Comment by roishmueli1** [comment]
did you uploded the last version  to github??
beucuse i am stil getting "Error: Cannot find module './book"

**Comment by roishmueli1** [comment]
try to write like this:       type: mongoose.Schema.ObjectId,

**Comment by yshur** [comment]
You right!! 
you are very big engineer!!
type: mongoose.Schema.ObjectId, was worked
now my project compiling well - i pushes my code to yair_branch
