### ISSUE TITLE
new Mlab account

### ISSUE THREAD

**Issue by roishmueli1** [yshur/eventbreak#5]
i opend for this project new mlab account because i dont have your details to connect your mlab, so lets work from this new account.

details to connect : 
user name: eventProject
password:  i sent you by mail

data base details:
db_usr:db_pass2

anyway, i did some collections and one document for each collection like what we did in the json format.

**Comment by roishmueli1** [comment]
i did not changed any line in the project... 
just to remeber how to work toghter on githab i did one commit in index.js

**Comment by yshur** [comment]
OK. 
I check the mlab later.
meanwhile i prefer the issue stay open until i will use this DB

**Comment by yshur** [comment]
I entered successfully to the new DB.
i added 's' to end of the name of collection "equipment".
i edit the const file to the new DB
